name: CheckForUpdates

on: #DO NOT CHANGE
  workflow_call: #https://docs.github.com/en/actions/learn-github-actions/reusing-workflows#creating-a-reusable-workflow
      inputs:
        templateRepo:
          required: true
          type: string
      secrets:
        PAT_RO:
          required: true


jobs:


  CheckForUpdates:
    #Dont put a template on a template
    if: ${{ !contains(github.event.repository.name , 'Template') }}
    runs-on: [self-hosted, linux, x64,L1]
    container:
       image: ghcr.io/setap2021/setapdocker   # Beware of versioning here GITHUB -- Some kind of magic here
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Clone Template Repo
      uses: actions/checkout@v2                            # 2
      with:
        repository:  ${{ inputs.templateRepo }}
        token: ${{ secrets.PAT_RO }}              # 4
        path: Template

    - name: Clone Student Repository (Latest)
      uses: actions/checkout@v2
      with:
        path: Student


    - name: Remove Protected files from template
      run: |
        cd Template/
        chmod +x .Ossonts/RemoveReservedFiles.sh
        .Ossonts/RemoveReservedFiles.sh
      shell: bash

    - name: Overlay updated files (if any)
      run: |
        Template/.Ossonts/CopyTemplateFilesToRepo.sh
        tree Template/
        tree Student/
        # echo "Template folder"
        # git -C Template  status
        echo "Student folder changes list:"
        git -C Student status

      shell: bash

      # Commit any updated files
    - uses: EndBug/add-and-commit@v7
      with:
        message: "Assessment UPDATE"
        cwd: 'Student/'

      env:
        GITHUB_TOKEN: ${{ secrets.PAT_RO }}
