name: CheckForUpdates

on: #DO NOT CHANGE
  workflow_call: #https://docs.github.com/en/actions/learn-github-actions/reusing-workflows#creating-a-reusable-workflow
      inputs:
        templateRepo:
          required: true
          type: string
      secrets:
        PAT_RO:
          required: true


jobs:


  CheckForUpdates:
    #Dont put a template on a template
    if: ${{ !contains(github.event.repository.name , 'Template') }}
    runs-on: [self-hosted, linux, x64,L1]
    container:
       image: ghcr.io/setap2021/setapdocker   # Beware of versioning here GITHUB -- Some kind of magic here
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Clone Template Repo
      uses: actions/checkout@v2                            # 2
      with:
        repository:  ${{ inputs.templateRepo }}
        token: ${{ secrets.PAT_RO }}              # 4
        path: Template

    - name: Clone Student Repository (Latest)
      uses: actions/checkout@v2
      with:
        path: Student


    - name: Remove Protected files from template
      run: |
        cd Template/
        #chmod +x .Ossonts/RemoveReservedFiles.sh
        #.Ossonts/RemoveReservedFiles.sh
        # This is a list of files that a student MIGHT have edited, -- so we dont want to overwrite.
        #Remove template files that should not be overwritten
        #You need to remove all files you want to keep :-)
        #Now any files I want to keep ?
        rm -fv CheckList.md
        rm -fv .pandoc.yml
        rm -fv Student.id ## Incase there is a testing ID in the system
        rm -fv Submit/*
        rm -fv Portfolio.md
        rm -fv CW.md
        rm -fv header.md
        rm -fv declaration.md
        rm -fv .Ossonts/*.log
        rm -fv .Ossonts/RemoveReservedFiles.sh
        rm -fv .github/workflows/CheckForUpdates.yml  # Dont trust updating the updater

      shell: bash

    - name: Overlay updated files (if any)
      run: |
        #Template/.Ossonts/CopyTemplateFilesToRepo.sh
        cp -vrf Template/* Student/
        cp -vrf Template/.Ossonts/* Student/.Ossonts/
        cp -vrf Template/.github/* Student/.github/
        cp -vrf Template/.vscode/* Student/.vscode/ || true
        tree Template/
        tree Student/
        # echo "Template folder"
        # git -C Template  status
        echo "Student folder changes list:"
        git -C Student status

      shell: bash

      # Commit any updated files
    - uses: EndBug/add-and-commit@v7
      with:
        message: "Assessment UPDATE"
        cwd: 'Student/'

      env:
        GITHUB_TOKEN: ${{ secrets.PAT_RO }}
