name: PlantUML

#take puml/* -> images/*

on:
  workflow_call: #https://docs.github.com/en/actions/learn-github-actions/reusing-workflows#creating-a-reusable-workflow

jobs:

  PlantUMLJob:
    #if: ${{ 1 == 2 }}
    #runs-on: ubuntu-20.04
    runs-on: [self-hosted, linux, x64,L2]
    container:
      image: ghcr.io/setap2021/setapdocker   # Beware of versioning here GITHUB -- Some kind of magic here
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: ExecutePlantUML
        run: |
            apt update
            apt install -y plantuml
            plantuml puml/*.puml -o ../image/

      - uses: EndBug/add-and-commit@v7
        with:
          message: "Plant UML"
          author_name: "OssontsBOT"
          #branch: feedback
          add:  "images/*"
          #tag: 'Submit --force'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}